cursor #e5e3d2
cursor_text_color #c8c8af

foreground            #e5e3d2
background            #13140a
selection_foreground  #1d361c
selection_background  #b0cfaa
url_color             #fbafe3

color0   #13140a
color1   #d75c3b
color2   #6ed682
color3   #d1db7b
color4   #ca5aa4
color5   #bc8ead
color6   #fbafe3
color7   #abb2bf
color8   #5c6370
color9   #e07a5f
color10  #86e096
color11  #dfe897
color12  #ffbcf2
color13  #b357a5
color14  #ab6289
color15  #ffffff
